FOLDER_TO_SAVE_PLOTS = 'output/plots'

FOLDER_TO_SAVE_WORD_COUNT_DICT = 'output/word_count'

SAVE_GRAPHS_TO_JPG = True

DISPLAY_PLOTTED_GRAPHS = False

LOG_GRAPH_SCALE = False

LINEAR_SCALE_LIMIT_OUTPUT_TO = 50
